services:
  postgres:
    image: postgres:16-alpine
    container_name: ai_support_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vivek
      POSTGRES_PASSWORD: devpassword123
      POSTGRES_DB: ai_support_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: